stages:
  - build
  - tests
  - publish

default:
  before_script:
    - dnf install -y rust cargo

build:
  stage: build
  tags:
    - linux
  script:
    - cargo build
  artifacts:
    untracked: true

unit-test:
  stage: tests
  needs: [build]
  tags:
    - linux
  script:
    - cargo test

build-and-publish:
  stage: publish
  needs: [unit-test]
  tags:
    - linux
  script:
    - cargo build --release
    - cargo login $CRATES_IO_API_TOKEN
    - cargo publish
  only:
    refs:
      - main

