[package]
name = "chmod-calculator"
version = "0.1.0"
authors = ["Chris Pilkington <chris.pilkington@gmail.com>"]
edition = "2024"

[[bin]]
name = "chmod-calculator"
path = "src/main.rs"

[dependencies]


[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"
assert_cmd = "2.0.17"
